name: dev_sdc_env
channels:
  - conda-forge
dependencies:
  - python<3.13
  - dask
  - dask-jobqueue>=0.8.5
  - dask-labextension
  - datashader
  - flox
  - geopandas
  - hvplot
  - jupyterlab>=4.1.0
  - jupyter-book
  - matplotlib
  - nodejs
  - numbagg>=0.8.0
  - odc-stac<=0.3.9
  - planetary-computer
  - rioxarray
  - rio-cogeo
  - rio-stac
  - spyndex
  - xarray>=2024.2.0
  - xarray-spatial
