name: dev_sdc_env
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - dask-jobqueue>=0.8.5
  - dask-labextension
  - datashader
  - fiona
  - flox
  - geopandas
  - hvplot
  - ipycytoscape
  - jupyterlab>=4.1.0
  - jupyter-book
  - matplotlib
  - numbagg>=0.8.0
  - odc-stac>=0.3.9
  - rioxarray
  - rio-cogeo
  - rio-stac
  - spyndex
  - xarray>=2024.2.0
  - xarray-spatial
