name: sdc_env
channels:
  - pyviz
  - conda-forge
dependencies:
  - python>=3.10
  - dask-jobqueue
  - odc-stac>=0.3.7
  - numbagg>=0.6.1
  - fiona
  - flox
############# Extras #############
  - pytz
  - spyndex
  - geopandas
  - rioxarray
  - scikit-learn
  - leafmap
  - matplotlib
  - hvplot
  - geoviews
  - datashader
  - autopep8
  - black
  - isort
  - ipympl
  - nodejs
  - jupyterlab=3.6.5
  - dask-labextension
  - jupyter-archive
  - jupyterlab-spellchecker
  - jupyterlab_code_formatter
  - jupyter-resource-usage<1.0.0
