name: sdc_env
channels:
  - pyviz
  - conda-forge
dependencies:
  - python>=3.10
  - dask-jobqueue
  - odc-stac>=0.3.7
  - numbagg>=0.6.1
  - fiona
  - flox
  - pytz
  - xarray-spatial
###### Extras - Geo / ML ######
  - spyndex
  - geopandas
  - rioxarray
  - scikit-learn
###### Extras - Visualization ######
  - leafmap
  - matplotlib
  - hvplot
  - geoviews
  - datashader
###### Extras - Jupyter ######
  - nodejs
  - jupyterlab
  - dask-labextension
  - jupyter-archive
