title: SALDi Data Cube - Tools & Tutorials
author: Marco Wolsza
copyright: "2023-2024"
logo: _assets/africa_map_iso.png

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: _latex/book.tex

bibtex_bibfiles:
  - _bibliography/references.bib

repository:
  url: https://github.com/Jena-Earth-Observation-School/sdc-tools
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  recursive_update: true
  config:
    html_context:
      default_mode: light
